[[files]]
path = "/etc/init.d/shuthost_host_agent"
perms = "750"
type = "OpenRC script"

[[files]]
path = "/etc/runlevels/default/shuthost_host_agent"
perms = "777"
type = "symbolic link to /etc/init.d/shuthost_host_agent"

[[files]]
path = "/usr/sbin/shuthost_host_agent"
perms = "755"
type = "ELF 64-bit LSB pie executable"

