[[files]]
path = "/etc/init.d/shuthost_coordinator"
perms = "750"
type = "OpenRC script"

[[files]]
path = "/etc/runlevels/default/shuthost_coordinator"
perms = "777"
type = "symbolic link to /etc/init.d/shuthost_coordinator"

[[files]]
path = "/home/root/.config/shuthost_coordinator/config.toml"
perms = "600"
type = "ASCII text"

[[files]]
path = "/home/root/.config/shuthost_coordinator/shuthost.db"
perms = "600"
type = "SQLite 3.x database"

[[files]]
path = "/home/root/.config/shuthost_coordinator/shuthost.db-shm"
perms = "600"
type = "SQLite Write-Ahead Log shared memory"

[[files]]
path = "/home/root/.config/shuthost_coordinator/shuthost.db-wal"
perms = "600"
type = "SQLite Write-Ahead Log"

[[files]]
path = "/usr/sbin/shuthost_coordinator"
perms = "755"
type = "ELF 64-bit LSB pie executable"

