[[files]]
path = "/workspace/shuthost_host_agent_self_extracting"
perms = "750"
type = "POSIX shell script"

[[files]]
path = "/workspace/shuthost_host_agent_self_extracting.ps1"
perms = "750"
type = "a pwsh script"

